# The chance a player will get caught while rummaging.
caught-chance: 0.1

# The time in ticks a user has before the
# mini-game inventory slots are randomized again.
minigame-roll-rate: 20

# The time the player must wait in seconds
# between pick-pocketing attempts.
# An attempt is when a player successfully
# pick-pockets another player.
cooldown-time: 10

# Allow players to disable pick-pocketing
# for themselves. This will also disallow others
# from pick-pocketing them.
allow-pickpocket-toggling: true

# Whether or not to show a players the
# pick-pocket status message when they attempt
# to pick-pocket another player whilst they, or the
# victim has pick-pocketing disabled.
show-status-on-interact: true

# Whether or not to show a players pick-pocket status when logging in.
show-status-on-login: true

# Items that can't be stolen and therefore, won't show
# up in the rummage GUI. A list of Minecraft IDs can be found
# at www.deadmap.com/idlist
disabled-items: [cake]