main: logan.pickpocket.main.Pickpocket
name: PickPocket
version: 1.1
author: TTG_TRE
api-version: 1.14
commands:
  pickpocket:
    aliases: pp
    description: Display help information for PickPocket.
    permission: pickpocket.use
