main: logan.pickpocket.main.PickpocketPlugin
name: PickPocket
version: 2.0-SNAPSHOT
author: TTG_TRE
api-version: 1.14
commands:
  pickpocket:
    aliases: pp
    description: Display help information for PickPocket.
    permission: pickpocket.use
